# Generated by Django 5.1.1 on 2024-10-06 00:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("car", "0002_alter_car_display"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="publishing_date",
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
